ardalis/DevIQ-gatsby

static/_redirects
See https://github.com/dotnet/docs/issues/22191
There must be more redirections that needs to be added. But those are what referenced currently in docs.microsoft.com
=> Add missing redirect

src/config/sidebar.yml
=> Added REPR to the sidebar

src/@rocketseat/gatsby-theme-docs/components/Announcement/index.js, src/@rocketseat/gatsby-theme-docs/components/Announcement/styles.js, src/@rocketseat/gatsby-theme-docs/components/Announcement/values.js, src/@rocketseat/gatsby-theme-docs/components/Layout/index.js, src/@rocketseat/gatsby-theme-docs/components/Layout/styles.js
@ardalis Can you review this one?
=> add announcement component

src/@rocketseat/gatsby-theme-docs/components/Announcement/index.js, src/@rocketseat/gatsby-theme-docs/components/Announcement/styles.js
@ardalis Just finished this one. Could you review this ?
=> enable user close announcement

src/docs/antipatterns/magic-strings.md
They weren't escaping anything and showed up on the actual page
(pretty sure my last PR didn't submit properly, so yea sorry if this is a duplicate)
=> Removed backslashes from magic-strings.md

src/docs/design-patterns/strategy-pattern.md
"Strategy" was missing an "r" in the second paragraph
=> Update strategy-pattern.md (small typo)

src/docs/laws/amaras-law.md, src/docs/laws/postels-law.md
trying out featuredImage which isn't yet enabled that I know of
=> adding amaras law

gatsby-config.js, package-lock.json, package.json
=> Adding an RSS feed for DevIQ

src/@rocketseat/gatsby-theme-docs/components/Docs/index.js, src/@rocketseat/gatsby-theme-docs/components/Layout/index.js
- Removing an unnecessary console.log
- Adding support for the featured image in SEO
=> Fixing og:image to use featured image

src/config/sidebar.yml, src/docs/domain-driven-design/context-mapping.md, src/docs/domain-driven-design/ddd-overview.md, src/docs/domain-driven-design/domain-storytelling.md
- Removing the Tools link
- Updating the DDD Overview with categories
- Updating Domain Storytelling and Context Mapping
=> Updating some DDD practices

src/@rocketseat/gatsby-theme-docs/components/Sidebar/ExternalLink/index.js, src/@rocketseat/gatsby-theme-docs/components/Sidebar/InternalLink/index.js, src/@rocketseat/gatsby-theme-docs/components/Sidebar/index.js, src/@rocketseat/gatsby-theme-docs/components/Sidebar/styles.js, src/@rocketseat/gatsby-theme-docs/util/copy-to-clipboard.js, src/@rocketseat/gatsby-theme-docs/util/slug.js, src/@rocketseat/gatsby-theme-docs/util/url.js
Closes #164 
Collapsed:
Each section is expandable:
Multiple sections can be expanded:
=> Updating the sidebar to be collapsible

gatsby-config.js, package-lock.json, package.json, src/config/sidebar.yml, src/pages/search.js
Closes #201 
Demo (animated GIF):
=> Adding Search to DevIQ

src/@rocketseat/gatsby-theme-docs/components/Sidebar/styles.js, src/@rocketseat/gatsby-theme-docs/text/index.mdx, src/config/sidebar.yml
=> Styling top links and adding magnifying glass

src/docs/laws/law-of-diminishing-returns.md, src/docs/values/respect.md
Existing descriptions:
Updated descriptions:
- Law of Diminishing Returns has a better description.
- Respect's description field now has the proper casing.
=> Updating description fields for Law of Diminishing Returns and Respect

src/config/sidebar.yml, src/docs/design-patterns/design-patterns-overview.md
=> Fixes broken menu, adds  Domain Events pattern to sidebar

src/docs/values/courage.md
This is queued up in SmarterQueue for Wednesday.
- Updated date, updated content to be more clear
- Fixed the reference to the featured image
=> Fixing incorrect featured image; updating text to be more clear

src/docs/principles/explicit-dependencies-principle.md
=> Updating explicit dependencies

src/docs/laws/laws-overview.md
=> Adding link to XP Simplicity Rules on Laws

gatsby-config.js, package-lock.json, package.json
- Adds gatsby-plugin-google-gtag based on configuration from NimblePros blog
- Potentially resolves #236
=> Add gatsby-plugin-google-gtag plugin

netlify.toml
=> Add npx playwright install as part of build commands for Netlify

package-lock.json, package.json
Closes #327 
Closes #312 
Closes #311 
Closes #310
=> Dependency updates  based on Dependabot recommendations

src/pages/search.js
=> Adding autoFocus

package.json, src/docs/practices/pain-driven-development.md
Tested locally and is working fine
Closes #342
Closes #362
Closes #375
Closes #376
Closes #377
Closes #386
Also fixes broken build
=> Dependency updates

src/docs/design-patterns/chain-of-responsibility-pattern.md
=> Fixing Chain of Responsibility description and image

src/docs/antipatterns/big-ball-of-mud.md, src/docs/antipatterns/witches-brew-architecture.md, src/docs/domain-driven-design/shared-kernel.md, src/docs/practices/yolo-architecture.md, src/docs/principles/separation-of-concerns.md
Now using academy.nimblepros.com!
=> Updating Clean Architecture course references

src/@rocketseat/gatsby-theme-docs/text/index.mdx
Tools and Terms weren't linked.
Now adding links for:
- Tools
- Terms
- Architecture
=> Home Page Updates
